import numpy as np

MODULATION_SIZE = 2**3
OVER_SAMPLING = 2

AMOUNT_OF_SYMBOLS = 2**16
SYMBOL_RATE = 41.80e9

SNR = 10
BETA = 0.01
THETA = np.pi/5.
TDGD = 30e-12
LINEWIDTH = 1e6
FREQ_OFFSET = 1e6

SEQUENCE_LENGTH = 2**5
LEARNING_RATE = 0.02
HIDDEN_NODES = 2**7
HIDDEN_LAYERS = 1

BATCH_SIZE = 2**7
TRAINING_RATIO = 0.9

USE_PULSESHAPING = True
USE_AGWN = True
USE_PMD = True
USE_PHASE_NOISE = False
USE_FREQ_OFFSET = False

PLOT_PICTURES = True
SHUFFLE = True
TENSORBOARD = False
BER = False
DISREGARD_OVERSAMPLING = False
USE_REAL_DATA = True
