import numpy as np

MODULATION_SIZE = 2**2
OVER_SAMPLING = 2

AMOUNT_OF_SYMBOLS = 2**16
SYMBOL_RATE = 25e9

SNR = 30
BETA = 0.1
THETA = np.pi/5.
TDGD = 20e-12
LINEWIDTH = 1e6
FREQ_OFFSET = 1e6

SEQUENCE_LENGTH = 2**6
LEARNING_RATE = 0.01
HIDDEN_NODES = 2**7
HIDDEN_LAYERS = 1

BATCH_SIZE = 2**10
TRAINING_RATIO = 0.9

USE_PULSESHAPING = True
USE_AGWN = True
USE_PMD = True
USE_PHASE_NOISE = True
USE_FREQ_OFFSET = True

PLOT_PICTURES = False
SHUFFLE = True
TENSORBOARD = False
BER = False
DISREGARD_OVERSAMPLING = False

ADD_PHASE = False
USE_BPS = True
